# Path to your oh-my-zsh installation.
ZSH_DISABLE_COMPFIX=true
autoload -U +X compinit && compinit
export ZSH=/Users/frederico.cabral/.oh-my-zsh

export EDITOR='vim'

# alias vim=/opt/homebrew/Cellar/vim/9.0.1350/bin/vim
alias vim='mvim -v'




# TMUXINATOR Completion
source ~/Workspace/dotfiles/tmux/tmuxinator/tmuxinator.zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

alias python="python3"


# Load rbenv automatically
eval "$(rbenv init - zsh)"



# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

#export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/workspace
eval "$(pyenv init -)"
#pyenv virtualenvwrapper_lazy
#source /usr/local/bin/virtualenvwrapper.sh


# GIT ALIAS
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gps='git push '
alias gpl='git pull '
alias gf='git fetch'
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '

curlj() {
  curl "$1" | jq
}


# local/bi
export PATH="/usr/local/bin:$PATH"

#KAFKA
export PATH="$PATH:/Users/frederico.cabral/kafka_2.12-2.0.0/bin"

#FLUTTER
export PATH="$PATH:/Users/frederico.cabral/workspace/flutter/bin"


#RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

#GO
export GOPATH=$HOME/workspace
export PATH=$PATH:$GOPATH/bin
export GOROOT="$(brew --prefix golang)/libexec"

#GOENV
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"



# added by travis gem
[ -f /Users/frederico.cabral/.travis/travis.sh ] && source /Users/frederico.cabral/.travis/travis.sh
#source /usr/local/opt/autoenv/activate.sh
#
#
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home

set -o vi
bindkey "^R" history-incremental-search-backward

export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/eksconfig
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH=$(pyenv root)/shims:$PATH


# Init goenv in the very end as it manipualte $PATH
eval "$(goenv init -)"

source ~/.variables.env
